// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF4Vcav5uraM2-AASNdDInfnOud1fLvG8',
    appId: '1:945592368118:web:57d81f9952a6d4933be5d7',
    messagingSenderId: '945592368118',
    projectId: 'card-game-a0bf7',
    authDomain: 'card-game-a0bf7.firebaseapp.com',
    storageBucket: 'card-game-a0bf7.firebasestorage.app',
    measurementId: 'G-Z5KNN9VBTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8WElDz8hr3y-6pvOF0600jZaHyHE3A0',
    appId: '1:945592368118:android:6801ec768bda1dd63be5d7',
    messagingSenderId: '945592368118',
    projectId: 'card-game-a0bf7',
    storageBucket: 'card-game-a0bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbyMEZypWE5_1wAr0Y65yN9yjeTj0X74',
    appId: '1:945592368118:ios:91dc987c0b29367b3be5d7',
    messagingSenderId: '945592368118',
    projectId: 'card-game-a0bf7',
    storageBucket: 'card-game-a0bf7.firebasestorage.app',
    iosBundleId: 'com.example.cardGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbyMEZypWE5_1wAr0Y65yN9yjeTj0X74',
    appId: '1:945592368118:ios:91dc987c0b29367b3be5d7',
    messagingSenderId: '945592368118',
    projectId: 'card-game-a0bf7',
    storageBucket: 'card-game-a0bf7.firebasestorage.app',
    iosBundleId: 'com.example.cardGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF4Vcav5uraM2-AASNdDInfnOud1fLvG8',
    appId: '1:945592368118:web:7fb1175f90a3b5c93be5d7',
    messagingSenderId: '945592368118',
    projectId: 'card-game-a0bf7',
    authDomain: 'card-game-a0bf7.firebaseapp.com',
    storageBucket: 'card-game-a0bf7.firebasestorage.app',
    measurementId: 'G-44QS1QC7J5',
  );
}
